// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
export interface User {
  readonly username: string; //key
  readonly name: string; //fields
  readonly lastname: string; //fields
  readonly phone: string; //fields
  readonly address: string; //fields
}